### ISSUE TITLE
TypeError: Invalid value used as weak map key

### ISSUE THREAD

**Issue by jperelli** [sindresorhus/camelcase-keys#15]
No idea why, but I was getting this error. Do you know if I'm using some sort of wrong value as a key in object?

ERROR RETURNED TO CLIENT:  TypeError: Invalid value used as weak map key
    at WeakMap.set (native)
    at mapObj (/home/jperelli/celerative/wysh/WYSHAPI/node_modules/map-obj/index.js:23:7)
    at module.exports (/home/jperelli/celerative/wysh/WYSHAPI/node_modules/camelcase-keys/index.js:16:9)
    at /home/jperelli/celerative/wysh/WYSHAPI/.webpack/service/app/requests/list.js:560:50
    at Array.map (native)
    at /home/jperelli/celerative/wysh/WYSHAPI/.webpack/service/app/requests/list.js:555:21
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)

**Comment by sindresorhus** [comment]
You're probably giving `camelCaseKeys()` a non-object.

**Comment by eliperkins** [comment]
This seems to be related to passing `null` to `camelcaseKeys`: https://runkit.com/eliperkins/59fb77dad46b990011223dbb

Should an `isObject` check get placed inside this library or do you think this should be left to the caller? I can open a PR to add a check, if so, but I feel like this might be overstepping the boundaries of this library.

**Comment by robwierzbowski** [comment]
I think it's best left to the caller. The docs specify [input type Object](https://github.com/sindresorhus/camelcase-keys#input); handling any other type of input gracefully feels like defensive coding which tends to bloat a project.

**Comment by jperelli** [comment]
I would argue that the error description gives no clue on how to fix this, so in this particular case it would be good to add an `if` to `camelcase-keys` lib

**Comment by cinderblock** [comment]
Instead of throwing an error, I think it would be better to just pass though invalid arguments.

**Comment by rameshrr** [comment]
Did you try the option `deep: true`

do not handle nested objects/arrays yourself, let the lib do it,
eg., `camelcaseKeys(data, { deep: true });`

**Comment by rameshrr** [comment]
Did you try the option `deep: true`

do not handle nested objects/arrays yourself, let the lib do it,
eg., `camelcaseKeys(data, { deep: true });`

**Comment by cinderblock** [comment]
@rameshrr That only works if the top level `data` is an object.

`camelcaseKeys(true, {deep: true})` throws.
